name: RainB0
version: '1.0'
main: com.black.minecraft.b0rain.B0rain
api-version: '1.18'
authors: [ b0b0b0 ]
website: https://black-minecraft.com/

commands:
  rainb0:
    description: Main command for RainB0 plugin
    usage: /<command> reload

permissions:
  rainb0.reload:
    description: Allows reloading RainB0 configuration
    default: op
